language: node_js
node_js: node
deploy:
  provider: heroku
    api_key:
      secure: fa36afce-6da7-4210-a508-86a84073a3b7
    app: exercise_app
    on:
      repo: https://github.com/clurdablur/exercise_app
